[package]
name = "pheasant_macro_fail"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[[bin]]
name = "dev"
path = "src/main.rs"

[dependencies]
pheasant_macro_utils = { version = "0.1.0", path = "../pheasant_macro_utils" }
