[package]
name = "pheasant_macro_post"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[[bin]]
path = "src/main.rs"
name = "dev"

[dependencies]
pheasant_macro_utils = { version = "0.1.0", path = "../pheasant_macro_utils" }

