[package]
name = "pheasant_macro_get"
version = "0.1.1"
edition = "2024"

[lib]
proc-macro = true

[[test]]
name = "basic"
path = "tests/basic.rs"

[[test]]
name = "mime"
path = "tests/mime.rs"

[[test]]
name = "re"
path = "tests/re.rs"

[[bin]]
path = "src/main.rs"
name = "dev"

[dependencies]
pheasant_macro_utils = { version = "0.1.0", path = "../pheasant_macro_utils" }
