[package]
name = "pheasant_headers"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
hashbrown = { workspace = true }
pheasant_core = { version = "0.1.0", path = "../pheasant_core" }
pheasant_uri = { version = "0.1.0", path = "../pheasant_uri" }
